### ISSUE TITLE
Standby battery issue

### ISSUE THREAD

**Issue by rodrigovet** [zeelog/OTA#2] opened 2020-07-31 16:47 UTC
Last build 3.18 kernel (lineage-17.1-20200721), standby high battery drain.
![photo_2020-07-30_20-04-56](https://user-images.githubusercontent.com/30162760/89057535-31791380-d334-11ea-9e90-bcd223310c51.jpg)

**Comment by zeelog** [comment] 2020-08-07 15:43
Couldn't reproduce issue with previous release, if anything try with the latest release & report back. Closing issue for now.

**Closed by zeelog** 2020-08-07 15:43 UTC
